stages: 
  - setup 
  - run 
 
setup_environment: 
  stage: setup 
  image: python:3.9 
  script: 
    - echo "Setting up environment" 
    - apt-get update && apt-get install -y gcc  # Install GCC 
    - echo "Environment setup complete." 
 
run_script: 
  stage: run 
  image: python:3.9 
  dependencies: 
    - setup_environment 
  script: 
    - apt-get update && apt-get install -y gcc  # Install GCC in this job as well (if needed) 
    - echo "Compiling Cpp file into binary..." 
    - g++ -o nuclear nuclear.cpp -std=c++11 -pthread  # Compile C file to binary 
    - pip install telebot pymongo aiohttp  # Install required Python dependencies 
    - chmod +x *  # Ensure all files are executable 
    - echo "Running the script..." 
    - python3 nuclear.py  # Run the Python script 
 
restart_pipeline: 
  stage: run 
  image: python:3.9 
  script: 
    - echo "Sleeping for 1 hour before restarting..." 
    - sleep 3600 
    - echo "Restarting the pipeline..." 
    - curl -X POST -F token=$CI_JOB_TOKEN -F ref=$CI_COMMIT_REF_NAME https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/trigger/pipeline 
  only: 
    - main  # Adjust if using a different branch